parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DataFixtures/'
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Model/'
            - '../src/Validator/Constraints/'
            - '../src/Kernel.php'

    App\Validator\Constraints\:
        resource: '../src/Validator/Constraints/**/*Validator.php'

when@dev:
    services:
        App\DataFixtures\:
            resource: '../src/DataFixtures/'
