parameters:
    app.movies.poster_path: '%kernel.project_dir%/assets/images/movies'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $posterAssetsPath: '%app.movies.poster_path%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DataFixtures/'
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Model/'
            - '../src/Validator/Constraints/'
            - '../src/Kernel.php'

    App\Validator\Constraints\:
        resource: '../src/Validator/Constraints/**/*Validator.php'

    # ------

    App\Omdb\Client\OmdbApiConsumerInterface: '@App\Omdb\Client\OmdbApiConsumer'

    App\Omdb\Bridge\AutomaticDatabaseImporter:
        decorates: 'App\Omdb\Client\OmdbApiConsumerInterface'
